# image
image: Visual Studio 2017

# build platform
platform: x64

# clone directory
clone_folder: c:\xmrig

install:
  - if not exist "c:\xmrig-dep" (mkdir c:\xmrig-dep & curl -sL https://github.com/xmrig/xmrig-deps/releases/download/v2/xmrig-deps-v2.zip -o xmrig-deps-v2.zip & 7z x xmrig-deps-v2.zip -o"c:\xmrig-dep" -y)
cache:
    - c:\xmrig-dep
build_script:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\VsMSBuildCmd.bat"
  - cd c:\xmrig
  - mkdir build
  - cd build
  - cmake .. -G "Visual Studio 15 2017 Win64" -DUV_INCLUDE_DIR=c:\xmrig-dep\libuv\include -DUV_LIBRARY=c:\xmrig-dep\libuv\Release\lib\libuv.lib
  - msbuild xmrig.sln /p:Configuration=Release

test_script:
  - cd c:\xmrig\build\bin\Release
  - copy ..\..\..\src\config.json .
  - tree /f
  
artifacts:
  - path: build\bin\Release
    name: xmrig-cpu-win
#  - xmrig.exe
