# image
image: Visual Studio 2017

# version
version: 1.0.{build}-{branch}

# build platform
platform: x64

# clone directory
clone_folder: c:\xmrig

install:
  - if not exist "c:\xmrig-dep" (mkdir c:\xmrig-dep & curl -sL https://github.com/xmrig/xmrig-deps/releases/download/v2/xmrig-deps-v2.zip -o xmrig-deps-v2.zip & 7z x xmrig-deps-v2.zip -o"c:\xmrig-dep" -y)
  - tree c:\xmrig-dep /f
cache:
    - c:\xmrig-dep
build_script:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\VsMSBuildCmd.bat"
  - cd %clone_folder%
  - mkdir build
  - cd build
  - cmake .. -G "Visual Studio 15 2017 Win64" -DUV_INCLUDE_DIR=c:\xmrig-dep\msvc2017\libuv\%platform%\include -DUV_LIBRARY=c:\xmrig-dep\msvc2017\libuv\%platform%\lib\libuv.lib -DMHD_INCLUDE_DIR=c:\xmrig-dep\msvc2017\libmicrohttpd\%platform%\include -DMHD_LIBRARY=c:\xmrig-dep\msvc2017\libmicrohttpd\%platform%\lib\libuv.lib
  - msbuild xmrig.sln /p:Configuration=Release

test_script:
  - cd c:\xmrig\build\Release
  - tree  /f
  - copy c:\xmrig\src\config.json .
  
artifacts:
  - path: build\Release
    name: xmrig-cpu-win
#  - xmrig.exe
